print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/harooniftikhar/AlienX/Assets/zombies/models/micro_zombie_brian.mb"`)
{		
	file -o "/Users/harooniftikhar/AlienX/Assets/zombies/models/micro_zombie_brian.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/harooniftikhar/AlienX/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/harooniftikhar/AlienX/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/harooniftikhar/AlienX/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
